-- Schema completo generado desde la base activa
-- Fuente: estructura actual sin datos
CREATE DATABASE IF NOT EXISTS maro_hub CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE maro_hub;

SET FOREIGN_KEY_CHECKS=0;

CREATE TABLE `acciones_preventivas` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `paciente_id` bigint unsigned NOT NULL,
  `td` date DEFAULT NULL,
  `tdpa` date DEFAULT NULL,
  `influenza` date DEFAULT NULL,
  `covid` date DEFAULT NULL,
  `otras` date DEFAULT NULL,
  `estomatologia` date DEFAULT NULL,
  `nutricion` date DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` bigint unsigned DEFAULT NULL,
  `updated_by` bigint unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_acciones_paciente` (`paciente_id`),
  CONSTRAINT `fk_acciones_paciente` FOREIGN KEY (`paciente_id`) REFERENCES `cat_pacientes` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `alertas_telegram` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `tipo` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `paciente_id` bigint NOT NULL,
  `consulta_id` bigint NOT NULL,
  `folio` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `unidad` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `puntaje_total` int NOT NULL,
  `payload_json` json DEFAULT NULL,
  `estado` enum('pendiente','enviado','error') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'pendiente',
  `intentos` int NOT NULL DEFAULT '0',
  `error_ultimo` text COLLATE utf8mb4_unicode_ci,
  `enviado_en` datetime DEFAULT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_alerta_consulta_tipo` (`consulta_id`,`tipo`),
  KEY `idx_alertas_estado_created` (`estado`,`created_at`),
  KEY `idx_alertas_paciente` (`paciente_id`),
  KEY `idx_alertas_consulta` (`consulta_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `bitacora` (
  `id` int NOT NULL AUTO_INCREMENT,
  `caso_id` int NOT NULL,
  `fecha_hora` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `actor_rol` enum('Médico','Coordinación','Experto') COLLATE utf8mb4_unicode_ci NOT NULL,
  `actor_nombre` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `accion` enum('CREA_CASO','SOLICITA_COLEGIACION','SOLICITA_INFO_ADICIONAL','ATIENDE_INFO_ADICIONAL','ACEPTA','RECHAZA','SESIONA','EMITE_RECOMENDACION','CIERRA') COLLATE utf8mb4_unicode_ci NOT NULL,
  `descripcion` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `fundamento` text COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`id`),
  KEY `idx_caso` (`caso_id`),
  KEY `idx_fecha` (`fecha_hora`),
  CONSTRAINT `bitacora_ibfk_1` FOREIGN KEY (`caso_id`) REFERENCES `casos` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `casos` (
  `id` int NOT NULL AUTO_INCREMENT,
  `folio` varchar(50) COLLATE utf8mb4_unicode_ci NOT NULL,
  `sesion_id` int DEFAULT NULL,
  `region` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `municipio` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `unidad` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `clues` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nivel_atencion` enum('Primer Nivel','Segundo Nivel','Tercer Nivel') COLLATE utf8mb4_unicode_ci NOT NULL,
  `paciente_iniciales` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL,
  `edad` int DEFAULT NULL,
  `semanas_gestacion` decimal(4,1) DEFAULT NULL,
  `trimestre` tinyint DEFAULT NULL,
  `gesta` int DEFAULT NULL,
  `partos` int DEFAULT NULL,
  `cesareas_previas` int DEFAULT NULL,
  `estatus` enum('BORRADOR','PENDIENTE_COLEGIACION','URGENCIA_REFERENCIA_2N','SOLICITADO_A_COLEGIACION','EN_ESPERA_DE_INFORMACION','RECHAZADO_POR_COORDINACION','ACEPTADO_PARA_COLEGIACION','CON_RECOMENDACION','CERRADO') COLLATE utf8mb4_unicode_ci DEFAULT 'BORRADOR',
  `nivel_riesgo` enum('AMARILLO','NARANJA','ROJO') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `score_riesgo` int DEFAULT NULL,
  `resumen_clinico` text COLLATE utf8mb4_unicode_ci,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `closed_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `folio` (`folio`),
  KEY `sesion_id` (`sesion_id`),
  KEY `idx_folio` (`folio`),
  KEY `idx_estatus` (`estatus`),
  KEY `idx_nivel_riesgo` (`nivel_riesgo`),
  KEY `idx_created` (`created_at`),
  CONSTRAINT `casos_ibfk_1` FOREIGN KEY (`sesion_id`) REFERENCES `sesiones` (`id`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `cat_pacientes` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `folio` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `region` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fecha_ingreso_cpn` date DEFAULT NULL,
  `clues_id` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `unidad` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `tipo_localidad` enum('Rural','Urbana') COLLATE utf8mb4_unicode_ci DEFAULT 'Urbana',
  `hospital_referencia` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `municipio` varchar(150) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `localidad` varchar(150) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `colonia` varchar(150) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `direccion` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `telefono` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `madrina_nombre` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `madrina_telefono` varchar(30) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `mecanismo_traslado` enum('Personal','Comunitario','Ninguno') COLLATE utf8mb4_unicode_ci DEFAULT 'Ninguno',
  `menarca` tinyint DEFAULT NULL,
  `gestas` tinyint DEFAULT NULL,
  `partos` tinyint DEFAULT NULL,
  `cesareas` tinyint DEFAULT NULL,
  `abortos` tinyint DEFAULT NULL,
  `ant_preeclampsia` tinyint(1) DEFAULT '0',
  `ant_hemorragia` tinyint(1) DEFAULT '0',
  `ant_sepsis` tinyint(1) DEFAULT '0',
  `ant_bajo_peso_macrosomia` tinyint(1) DEFAULT '0',
  `ant_muerte_perinatal` tinyint(1) DEFAULT '0',
  `fum` date DEFAULT NULL,
  `fpp` date DEFAULT NULL,
  `semanas_gestacion` decimal(4,1) DEFAULT NULL,
  `sdg_ingreso` tinyint DEFAULT NULL,
  `factores_riesgo_old` text COLLATE utf8mb4_unicode_ci COMMENT 'Campo antiguo - mantener por respaldo',
  `factores_riesgo_epid_old` text COLLATE utf8mb4_unicode_ci COMMENT 'Campo antiguo - mantener por respaldo',
  `factores_riesgo_epid` enum('ninguno','es_contacto','es_portadora') COLLATE utf8mb4_unicode_ci DEFAULT 'ninguno' COMMENT 'Factores epidemiológicos: ninguno=0pts, es_contacto=4pts, es_portadora=6pts',
  `imc_inicial` decimal(5,2) DEFAULT NULL,
  `ganancia_ponderal_max` decimal(5,2) DEFAULT NULL,
  `tipo_riesgo_social` enum('Bajo','Medio','Alto') COLLATE utf8mb4_unicode_ci DEFAULT 'Bajo',
  `riesgo_obstetrico_ingreso` tinyint DEFAULT NULL,
  `nombre_completo` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `curp` char(18) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `edad` tinyint DEFAULT NULL,
  `indigena` tinyint(1) DEFAULT '0',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` bigint unsigned DEFAULT NULL,
  `updated_by` bigint unsigned DEFAULT NULL,
  `factor_diabetes` tinyint(1) DEFAULT '0' COMMENT 'Diabetes (4 puntos)',
  `factor_hipertension` tinyint(1) DEFAULT '0' COMMENT 'Hipertensión (4 puntos)',
  `factor_obesidad` tinyint(1) DEFAULT '0' COMMENT 'Obesidad (4 puntos)',
  `factor_cardiopatia` tinyint(1) DEFAULT '0' COMMENT 'Cardiopatía (4 puntos)',
  `factor_hepatopatia` tinyint(1) DEFAULT '0' COMMENT 'Hepatopatía (4 puntos)',
  `factor_enf_autoinmune` tinyint(1) DEFAULT '0' COMMENT 'Enfermedad autoinmune (4 puntos)',
  `factor_nefropatia` tinyint(1) DEFAULT '0' COMMENT 'Nefropatía (4 puntos)',
  `factor_coagulopatias` tinyint(1) DEFAULT '0' COMMENT 'Coagulopatías (4 puntos)',
  `factor_neuropatia` tinyint(1) DEFAULT '0' COMMENT 'Neuropatía (4 puntos)',
  `factor_enf_psiquiatrica` tinyint(1) DEFAULT '0' COMMENT 'Enfermedad psiquiátrica (4 puntos)',
  `factor_alcoholismo` tinyint(1) DEFAULT '0' COMMENT 'Alcoholismo (4 puntos)',
  `factor_tabaquismo` tinyint(1) DEFAULT '0' COMMENT 'Tabaquismo (2 puntos)',
  `factor_drogas_ilicitas` tinyint(1) DEFAULT '0' COMMENT 'Drogas ilícitas (4 puntos)',
  `factor_riesgo_antecedentes` int DEFAULT '0' COMMENT 'Sumatoria de puntos de factores de riesgo por antecedentes (0-100)',
  `fecha_actualizacion_riesgo` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT 'Última fecha de actualización del factor de riesgo',
  `factor_riesgo_tamizajes` int DEFAULT '0' COMMENT 'Sumatoria de puntos de factores de riesgo por tamizajes iniciales (0-20)',
  PRIMARY KEY (`id`),
  UNIQUE KEY `folio` (`folio`),
  KEY `idx_pacientes_clues` (`clues_id`),
  KEY `idx_pacientes_region` (`region`),
  KEY `idx_factor_riesgo_tamizajes` (`factor_riesgo_tamizajes`),
  CONSTRAINT `fk_pacientes_clues` FOREIGN KEY (`clues_id`) REFERENCES `cat_unidades` (`clues`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `cat_unidades` (
  `clues` varchar(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  `unidad` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `region` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `municipio` varchar(150) COLLATE utf8mb4_unicode_ci NOT NULL,
  `nivel` tinyint NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`clues`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `colegiados_acciones` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `plan_id` bigint unsigned NOT NULL,
  `nivel_atencion` enum('primer_nivel','segundo_nivel','tercer_nivel') COLLATE utf8mb4_unicode_ci NOT NULL,
  `orden` tinyint unsigned NOT NULL,
  `descripcion` varchar(500) COLLATE utf8mb4_unicode_ci NOT NULL,
  `cumplido` tinyint(1) NOT NULL DEFAULT '0',
  `fecha_cumplimiento` datetime DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_colegiados_acciones_orden` (`plan_id`,`nivel_atencion`,`orden`),
  KEY `idx_colegiados_acciones_plan_nivel` (`plan_id`,`nivel_atencion`),
  CONSTRAINT `fk_colegiados_acciones_plan` FOREIGN KEY (`plan_id`) REFERENCES `colegiados_planes` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `colegiados_planes` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `consulta_id` bigint unsigned NOT NULL,
  `paciente_id` bigint unsigned NOT NULL,
  `estatus` enum('borrador','completo') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'borrador',
  `observaciones` text COLLATE utf8mb4_unicode_ci,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_colegiados_planes_consulta` (`consulta_id`),
  KEY `idx_colegiados_planes_paciente` (`paciente_id`),
  CONSTRAINT `fk_colegiados_planes_consulta` FOREIGN KEY (`consulta_id`) REFERENCES `consultas_prenatales` (`id`),
  CONSTRAINT `fk_colegiados_planes_paciente` FOREIGN KEY (`paciente_id`) REFERENCES `cat_pacientes` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `consultas_prenatales` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `paciente_id` bigint unsigned NOT NULL,
  `fecha_consulta` date NOT NULL,
  `sdg` tinyint DEFAULT NULL,
  `peso` decimal(5,2) DEFAULT NULL,
  `imc` decimal(5,2) DEFAULT NULL,
  `ta_sistolica` smallint DEFAULT NULL,
  `ta_diastolica` smallint DEFAULT NULL,
  `frecuencia_cardiaca` smallint DEFAULT NULL,
  `indice_choque` decimal(5,2) DEFAULT NULL,
  `frecuencia_respiratoria` smallint DEFAULT NULL,
  `temperatura` decimal(4,1) DEFAULT NULL,
  `glucosa_capilar` decimal(5,2) DEFAULT NULL,
  `altura_uterina` decimal(4,1) DEFAULT NULL,
  `fondo_uterino_acorde_sdg` tinyint(1) DEFAULT '0',
  `ivu_repeticion` tinyint(1) DEFAULT '0',
  `estado_conciencia` enum('alteraciones','conciente') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `hemorragia` enum('visible o abundante','no visible o moderada','no visible o escasa') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `respiracion` enum('alterada','normal') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `color_piel` enum('cianotica','palida','normal') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `puntaje_consulta_parametros` int NOT NULL DEFAULT '0',
  `puntaje_total_consulta` int NOT NULL DEFAULT '0',
  `riesgo_25_plus` tinyint(1) NOT NULL DEFAULT '0',
  `colegiado` tinyint(1) NOT NULL DEFAULT '0',
  `fecha_colegiado` datetime DEFAULT NULL,
  `diagnostico` enum('seguimiento_embarazo','puerperio') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `plan` text COLLATE utf8mb4_unicode_ci,
  `fecha_referencia` date DEFAULT NULL,
  `area_referencia` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `fcf` smallint DEFAULT NULL,
  `movimientos_fetales` tinyint(1) DEFAULT NULL,
  `proteinuria` enum('Neg','Tr','+','++','+++') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `edema` enum('No','MMII','Generalizado') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `notas` text COLLATE utf8mb4_unicode_ci,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` bigint unsigned DEFAULT NULL,
  `updated_by` bigint unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_consultas_paciente` (`paciente_id`),
  KEY `idx_consultas_puntaje_total` (`puntaje_total_consulta`),
  KEY `idx_consultas_riesgo_25_plus` (`riesgo_25_plus`),
  KEY `idx_consultas_riesgo_fecha` (`riesgo_25_plus`,`fecha_consulta`),
  KEY `idx_consultas_colegiado` (`colegiado`),
  KEY `idx_consultas_fecha_colegiado` (`fecha_colegiado`),
  CONSTRAINT `fk_consultas_paciente` FOREIGN KEY (`paciente_id`) REFERENCES `cat_pacientes` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `detecciones` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `paciente_id` bigint unsigned NOT NULL,
  `prueba_vih` enum('Reactiva','No reactiva') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `prueba_vdrl` enum('Reactiva','No reactiva') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `prueba_hepatitis_c` enum('Reactiva','No reactiva') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `prueba_vih_t3` enum('Reactiva','No reactiva') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `prueba_vdrl_t3` enum('Reactiva','No reactiva') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `prueba_hepatitis_c_t3` enum('Reactiva','No reactiva') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `diabetes_glicemia` enum('Normal','Resistencia a la insulina','Diabetes') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `violencia` enum('Positiva','Negativa') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` bigint unsigned DEFAULT NULL,
  `updated_by` bigint unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `fk_detecciones_paciente` (`paciente_id`),
  CONSTRAINT `fk_detecciones_paciente` FOREIGN KEY (`paciente_id`) REFERENCES `cat_pacientes` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `diagnosticos` (
  `id` int NOT NULL AUTO_INCREMENT,
  `caso_id` int NOT NULL,
  `diagnostico` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_caso` (`caso_id`),
  CONSTRAINT `diagnosticos_ibfk_1` FOREIGN KEY (`caso_id`) REFERENCES `casos` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `estudios` (
  `id` int NOT NULL AUTO_INCREMENT,
  `caso_id` int NOT NULL,
  `estudio` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `resultado` text COLLATE utf8mb4_unicode_ci,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_caso` (`caso_id`),
  CONSTRAINT `estudios_ibfk_1` FOREIGN KEY (`caso_id`) REFERENCES `casos` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `evaluaciones_clinicas` (
  `id` int NOT NULL AUTO_INCREMENT,
  `caso_id` int NOT NULL,
  `embarazo_multiple` tinyint(1) DEFAULT '0',
  `antecedente_preeclampsia` tinyint(1) DEFAULT '0',
  `antecedente_hemorragia` tinyint(1) DEFAULT '0',
  `diabetes_previa` tinyint(1) DEFAULT '0',
  `diabetes_gestacional` tinyint(1) DEFAULT '0',
  `hipertension_cronica` tinyint(1) DEFAULT '0',
  `cardiopatia` tinyint(1) DEFAULT '0',
  `nefropatia` tinyint(1) DEFAULT '0',
  `epilepsia` tinyint(1) DEFAULT '0',
  `vih` tinyint(1) DEFAULT '0',
  `sangrado_vaginal` tinyint(1) DEFAULT '0',
  `salida_liquido` tinyint(1) DEFAULT '0',
  `dolor_abdominal_intenso` tinyint(1) DEFAULT '0',
  `cefalea_severa` tinyint(1) DEFAULT '0',
  `fosfenos` tinyint(1) DEFAULT '0',
  `epigastralgia` tinyint(1) DEFAULT '0',
  `convulsiones` tinyint(1) DEFAULT '0',
  `fiebre` tinyint(1) DEFAULT '0',
  `disnea` tinyint(1) DEFAULT '0',
  `dolor_toracico` tinyint(1) DEFAULT '0',
  `alteracion_estado_mental` tinyint(1) DEFAULT '0',
  `disminucion_movimientos_fetales` tinyint(1) DEFAULT '0',
  `sistolica` int DEFAULT NULL,
  `diastolica` int DEFAULT NULL,
  `frecuencia_cardiaca` int DEFAULT NULL,
  `frecuencia_respiratoria` int DEFAULT NULL,
  `saturacion_o2` decimal(5,2) DEFAULT NULL,
  `temperatura` decimal(4,2) DEFAULT NULL,
  `plaquetas` int DEFAULT NULL,
  `creatinina` decimal(5,2) DEFAULT NULL,
  `ast` int DEFAULT NULL,
  `alt` int DEFAULT NULL,
  `proteinuria_tira` enum('NEG','TRAZA','1+','2+','3+','4+') COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `peso_kg` decimal(5,2) DEFAULT NULL,
  `talla_cm` decimal(5,2) DEFAULT NULL,
  `imc` decimal(5,2) DEFAULT NULL,
  `fondo_uterino_cm` decimal(4,1) DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_caso` (`caso_id`),
  CONSTRAINT `evaluaciones_clinicas_ibfk_1` FOREIGN KEY (`caso_id`) REFERENCES `casos` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `puerperio` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `paciente_id` bigint unsigned DEFAULT NULL,
  `folio` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `complicaciones` text COLLATE utf8mb4_unicode_ci,
  `MMEG` tinyint(1) DEFAULT '0',
  `fecha_atencion_evento` date DEFAULT NULL,
  `dias_puerperio` int DEFAULT NULL,
  `valoracion_riesgo` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `apeo_fecha` date DEFAULT NULL,
  `apeo_metodo` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `datos_alarma` text COLLATE utf8mb4_unicode_ci,
  `diagnostico` varchar(200) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `plan` text COLLATE utf8mb4_unicode_ci,
  `fecha_siguiente_consulta` date DEFAULT NULL,
  `referencia` text COLLATE utf8mb4_unicode_ci,
  `usuaria_seguimiento` tinyint(1) DEFAULT '0',
  `fecha_atencion_sna_tna` date DEFAULT NULL,
  `fecha_contrareferencia` date DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `created_by` bigint unsigned DEFAULT NULL,
  `updated_by` bigint unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_puerperio_paciente` (`paciente_id`),
  KEY `idx_puerperio_folio` (`folio`),
  CONSTRAINT `fk_puerperio_paciente` FOREIGN KEY (`paciente_id`) REFERENCES `cat_pacientes` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `recomendaciones` (
  `id` int NOT NULL AUTO_INCREMENT,
  `caso_id` int NOT NULL,
  `conducta` text COLLATE utf8mb4_unicode_ci NOT NULL,
  `nivel_atencion` enum('Primer Nivel','Segundo Nivel','Tercer Nivel') COLLATE utf8mb4_unicode_ci NOT NULL,
  `urgencia` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `observaciones` text COLLATE utf8mb4_unicode_ci,
  `fecha` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_caso` (`caso_id`),
  CONSTRAINT `recomendaciones_ibfk_1` FOREIGN KEY (`caso_id`) REFERENCES `casos` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `sesiones` (
  `id` int NOT NULL AUTO_INCREMENT,
  `region` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `municipio` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `unidad` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `clues` varchar(50) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_region` (`region`),
  KEY `idx_municipio` (`municipio`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE `usuarios` (
  `id` int NOT NULL AUTO_INCREMENT,
  `username` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL,
  `password_hash` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `nombre` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `nivel` enum('CLUES','REGION','ESTADO','ADMIN') COLLATE utf8mb4_unicode_ci NOT NULL,
  `clues_id` varchar(20) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `region` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `activo` tinyint(1) NOT NULL DEFAULT '1',
  `must_change_password` tinyint(1) NOT NULL DEFAULT '1',
  `last_login_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `username` (`username`),
  KEY `clues_id` (`clues_id`),
  KEY `idx_usuarios_nivel_region` (`nivel`,`region`),
  KEY `idx_usuarios_nivel_clues` (`nivel`,`clues_id`),
  CONSTRAINT `usuarios_ibfk_1` FOREIGN KEY (`clues_id`) REFERENCES `cat_unidades` (`clues`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS=1;
