-- Creación de tablas para pacientes y consultas prenatales

CREATE TABLE IF NOT EXISTS cat_pacientes (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  folio VARCHAR(50) UNIQUE,
  region VARCHAR(100),
  fecha_ingreso_cpn DATE,
  clues_id VARCHAR(20) COLLATE utf8mb4_unicode_ci NOT NULL,
  unidad VARCHAR(200),
  tipo_localidad ENUM('Rural','Urbana') DEFAULT 'Urbana',
  hospital_referencia VARCHAR(200),
  municipio VARCHAR(150),
  localidad VARCHAR(150),
  colonia VARCHAR(150),
  direccion VARCHAR(255),
  telefono VARCHAR(30),
  madrina_nombre VARCHAR(200),
  madrina_telefono VARCHAR(30),
  mecanismo_traslado ENUM('Personal','Comunitario','Ninguno') DEFAULT 'Ninguno',
  menarca TINYINT,
  gestas TINYINT,
  partos TINYINT,
  cesareas TINYINT,
  abortos TINYINT,
  ant_preeclampsia BOOLEAN DEFAULT FALSE,
  ant_hemorragia BOOLEAN DEFAULT FALSE,
  ant_sepsis BOOLEAN DEFAULT FALSE,
  ant_bajo_peso_macrosomia BOOLEAN DEFAULT FALSE,
  ant_muerte_perinatal BOOLEAN DEFAULT FALSE,
  fum DATE,
  fpp DATE,
  sdg_ingreso TINYINT,
  factores_riesgo TEXT,
  factores_riesgo_epid TEXT,
  imc_inicial DECIMAL(5,2),
  ganancia_ponderal_max DECIMAL(5,2),
  tipo_riesgo_social ENUM('Bajo','Medio','Alto') DEFAULT 'Bajo',
  riesgo_obstetrico_ingreso TINYINT,
  nombre_completo VARCHAR(255),
  curp CHAR(18),
  edad TINYINT,
  indigena BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by BIGINT UNSIGNED,
  updated_by BIGINT UNSIGNED,
  CONSTRAINT fk_pacientes_clues FOREIGN KEY (clues_id) REFERENCES cat_unidades(clues)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS consultas_prenatales (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  paciente_id BIGINT UNSIGNED NOT NULL,
  fecha_consulta DATE NOT NULL,
  sdg TINYINT,
  peso DECIMAL(5,2),
  imc DECIMAL(5,2),
  ta_sistolica SMALLINT,
  ta_diastolica SMALLINT,
  glucosa_capilar DECIMAL(5,2),
  altura_uterina DECIMAL(4,1),
  fcf SMALLINT,
  movimientos_fetales BOOLEAN,
  proteinuria ENUM('Neg','Tr','+','++','+++'),
  edema ENUM('No','MMII','Generalizado'),
  notas TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  created_by BIGINT UNSIGNED,
  updated_by BIGINT UNSIGNED,
  CONSTRAINT fk_consultas_paciente FOREIGN KEY (paciente_id) REFERENCES cat_pacientes(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE INDEX idx_pacientes_clues ON cat_pacientes(clues_id);
CREATE INDEX idx_pacientes_region ON cat_pacientes(region);
CREATE INDEX idx_consultas_paciente ON consultas_prenatales(paciente_id);
