SELECT 
    p.id AS Paciente_ID,
    p.folio AS Paciente_Folio,
    p.nombre_completo AS Paciente_Nombre,
    p.curp AS Paciente_CURP,
    p.edad AS Paciente_Edad,
    p.telefono AS Paciente_Telefono,
    p.tipo_localidad AS Localidad_Tipo,
    p.municipio AS Paciente_Municipio,
    p.localidad AS Paciente_Localidad,
    p.colonia AS Paciente_Colonia,
    p.direccion AS Paciente_Direccion,
    IF(p.indigena = 1, 'Sí', 'No') AS Paciente_Es_Indigena,
    IF(p.migrante = 1, 'Sí', 'No') AS Paciente_Es_Migrante,
    p.derechohabiencia AS Paciente_Derechohabiencia,
    p.hospital_referencia AS Hospital_Referencia_Asignado,
    p.madrina_nombre AS Madrina_Nombre,
    p.madrina_telefono AS Madrina_Telefono,
    p.mecanismo_traslado AS Mecanismo_Traslado,
    p.fecha_ingreso_cpn AS Fecha_Ingreso_CPN,
    u.clues AS Unidad_CLUES,
    u.unidad AS Unidad_Nombre,
    u.region AS Unidad_Region,
    u.municipio AS Unidad_Municipio,
    u.nivel AS Unidad_Nivel_Atencion,
    p.menarca AS Antecedente_Menarca,
    p.gestas AS Antecedente_Gestas,
    p.partos AS Antecedente_Partos,
    p.cesareas AS Antecedente_Cesareas,
    p.abortos AS Antecedente_Abortos,
    p.fum AS Fecha_FUM,
    p.fpp AS Fecha_FPP,
    p.semanas_gestacion AS SDG_Calculadas,
    p.sdg_ingreso AS SDG_Al_Ingreso,
    p.imc_inicial AS IMC_Inicial,
    p.ganancia_ponderal_max AS Ganancia_Ponderal_Max_Permitida,
    p.tipo_riesgo_social AS Riesgo_Social,
    p.riesgo_obstetrico_ingreso AS Riesgo_Obstetrico_Ingreso,
    IF(p.ant_preeclampsia = 1, 'Sí', 'No') AS Historial_Preeclampsia,
    IF(p.ant_hemorragia = 1, 'Sí', 'No') AS Historial_Hemorragia,
    IF(p.ant_sepsis = 1, 'Sí', 'No') AS Historial_Sepsis,
    IF(p.ant_bajo_peso_macrosomia = 1, 'Sí', 'No') AS Historial_BajoPeso_Macrosomia,
    IF(p.ant_muerte_perinatal = 1, 'Sí', 'No') AS Historial_Muerte_Perinatal,
    IF(p.ant_embarazo_ectopico = 1, 'Sí', 'No') AS Historial_Embarazo_Ectopico,
    IF(p.factor_diabetes = 1, 'Sí', 'No') AS Factor_Diabetes,
    IF(p.factor_hipertension = 1, 'Sí', 'No') AS Factor_Hipertension,
    IF(p.factor_obesidad = 1, 'Sí', 'No') AS Factor_Obesidad,
    IF(p.factor_cardiopatia = 1, 'Sí', 'No') AS Factor_Cardiopatia,
    IF(p.factor_hepatopatia = 1, 'Sí', 'No') AS Factor_Hepatopatia,
    IF(p.factor_enf_autoinmune = 1, 'Sí', 'No') AS Factor_Enf_Autoinmune,
    IF(p.factor_nefropatia = 1, 'Sí', 'No') AS Factor_Nefropatia,
    IF(p.factor_coagulopatias = 1, 'Sí', 'No') AS Factor_Coagulopatias,
    IF(p.factor_neuropatia = 1, 'Sí', 'No') AS Factor_Neuropatia,
    IF(p.factor_enf_psiquiatrica = 1, 'Sí', 'No') AS Factor_Enf_Psiquiatrica,
    IF(p.factor_drogas_ilicitas = 1, 'Sí', 'No') AS Factor_Otras_Drogas,
    IF(p.factor_endocrinopatia = 1, 'Sí', 'No') AS Factor_Endocrinopatia,
    IF(p.factor_neumopatia = 1, 'Sí', 'No') AS Factor_Neumopatia,
    IF(p.factor_its = 1, 'Sí', 'No') AS Factor_ITS,
    IF(p.factor_cirugias_pelvico_uterinas = 1, 'Sí', 'No') AS Factor_Cirugias_Pelvico_Uterinas,
    IF(p.factor_discapacidad = 1, 'Sí', 'No') AS Factor_Discapacidad,
    p.factores_riesgo_epid AS Factor_Riesgo_Epidemiologico,
    p.factor_riesgo_antecedentes AS Score_Riesgo_Antecedentes,
    p.factor_riesgo_tamizajes AS Score_Riesgo_Tamizajes,
    ap.td AS Vacuna_TD_Fecha,
    ap.tdpa AS Vacuna_TDPA_Fecha,
    ap.influenza AS Vacuna_Influenza_Fecha,
    ap.covid AS Vacuna_Covid_Fecha,
    ap.otras AS Vacunas_Otras_Fecha,
    ap.estomatologia AS Consulta_Estomatologia_Fecha,
    ap.nutricion AS Consulta_Nutricion_Fecha,
    det.prueba_vih AS Deteccion_VIH_T1,
    det.prueba_vdrl AS Deteccion_VDRL_T1,
    det.prueba_hepatitis_c AS Deteccion_HepatitisC_T1,
    det.prueba_vih_t3 AS Deteccion_VIH_T3,
    det.prueba_vdrl_t3 AS Deteccion_VDRL_T3,
    det.prueba_hepatitis_c_t3 AS Deteccion_HepatitisC_T3,
    det.diabetes_glicemia AS Tamizaje_Glicemia,
    det.violencia AS Tamizaje_Violencia,
    c.id AS Consulta_ID,
    c.fecha_consulta AS Consulta_Fecha,
    c.sdg AS Consulta_SDG,
    c.peso AS Consulta_Peso_Kg,
    c.imc AS Consulta_IMC,
    CONCAT(c.ta_sistolica, '/', c.ta_diastolica) AS Consulta_Tension_Arterial,
    c.frecuencia_cardiaca AS Consulta_FC_Madre,
    c.frecuencia_respiratoria AS Consulta_FR,
    c.temperatura AS Consulta_Temperatura_C,
    c.glucosa_capilar AS Consulta_Glucosa_Capilar,
    c.altura_uterina AS Consulta_Altura_Uterina_cm,
    IF(c.fondo_uterino_acorde_sdg = 1, 'Sí', 'No') AS Consulta_FondoUterino_Accorde,
    c.fcf AS Consulta_FC_Fetal,
    IF(c.movimientos_fetales = 1, 'Sí', 'No') AS Consulta_Mov_Fetales,
    c.proteinuria AS Consulta_Proteinuria_Tira,
    c.edema AS Consulta_Edema,
    c.estado_conciencia AS Consulta_Estado_Conciencia,
    c.hemorragia AS Consulta_Hemorragia_Estatus,
    c.color_piel AS Consulta_Color_Piel,
    c.puntaje_total_consulta AS Consulta_Score_Puntaje_Total,
    IF(c.riesgo_25_plus = 1, 'ALTO RIESGO (25+)', 'Normal') AS Consulta_Riesgo_Alerta,
    IF(c.colegiado = 1, 'Sí', 'No') AS Consulta_Fue_Colegiado,
    c.diagnostico AS Consulta_Diagnostico,
    c.plan AS Consulta_Plan_Indicaciones,
    c.notas AS Consulta_Notas_Clinicas,
    cp.id AS Plan_Colegiado_ID,
    cp.estatus AS Plan_Colegiado_Estatus,
    cp.observaciones AS Plan_Colegiado_Observaciones,
    ca.nivel_atencion AS Plan_Accion_Nivel,
    ca.orden AS Plan_Accion_Orden_Paso,
    ca.descripcion AS Plan_Accion_Descripcion,
    IF(ca.cumplido = 1, 'Cumplido', 'Pendiente') AS Plan_Accion_Estatus,
    ca.fecha_cumplimiento AS Plan_Accion_Fecha_Cumplimiento,
    pu.id AS Puerperio_ID,
    pu.fecha_atencion_evento AS Puerperio_Fecha_Evento,
    pu.dias_puerperio AS Puerperio_Dias_Transcurridos,
    pu.complicaciones AS Puerperio_Complicaciones,
    IF(pu.MMEG = 1, 'Sí', 'No') AS Puerperio_MMEG,
    pu.valoracion_riesgo AS Puerperio_Valoracion_Riesgo,
    pu.apeo_metodo AS Puerperio_APEO_Metodo,
    pu.apeo_fecha AS Puerperio_APEO_Fecha,
    pu.datos_alarma AS Puerperio_Datos_Alarma_Identificados,
    pu.diagnostico AS Puerperio_Diagnostico,
    pu.plan AS Puerperio_Plan
FROM cat_pacientes p
INNER JOIN cat_unidades u ON p.clues_id = u.clues
LEFT JOIN acciones_preventivas ap ON p.id = ap.paciente_id
LEFT JOIN detecciones det ON p.id = det.paciente_id
LEFT JOIN consultas_prenatales c ON p.id = c.paciente_id
LEFT JOIN colegiados_planes cp ON c.id = cp.consulta_id AND p.id = cp.paciente_id
LEFT JOIN colegiados_acciones ca ON cp.id = ca.plan_id
LEFT JOIN puerperio pu ON p.id = pu.paciente_id;